name: zams_python
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy=1.24.3
  - pandas=2.0.0
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - jupyter=1.0.0
  - notebook=6.5.4
  - ipykernel=6.22.0
  - ipywidgets
  - pip:
    - pytest==7.3.1
    - flake8==6.0.0
    - black==23.3.0
    - colorama
    - nbconvert==7.3.1 